language: cpp

compiler: gcc

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -y build-essential
  - sudo apt-get install -y cmake libboost-date-time-dev libboost-thread-dev libboost-system-dev
  - sudo apt-get install -y libportmidi-dev libsqlite3-0 libsqlite3-dev
  - sudo apt-get install -y libfreetype6-dev libpng++-dev zlib1g-dev libwxgtk3.0-dev

before_script:
  - mkdir build
  - cd build
  - cmake -G "Unix Makefiles"  ..

script:
  - make

notifications:
  email:
    - s.cecilio@gmail.com
  irc:
    channels:
    - "irc.freenode.net#lenmus"
    template:
    - "Build #%{build_number} at %{repository_slug}/%{branch} took %{duration}"
    - "%{author} %{commit} \"%{commit_message}\" %{compare_url}"
    - "%{message} %{build_url}"
